
-- Base : 기본 데미지
-- Bonus : 레벨 당 보너스 데미지


CHAR0_BASE_ATK = 10;
CHAR0_BONUS_ATK = 2;
CHAR0_BASE_SKILL = 20;
CHAR0_BONUS_SKILL = 5;

CHAR1_BASE_ATK = 15;
CHAR1_BONUS_ATK = 3;
CHAR1_BASE_SKILL = 20;
CHAR1_BONUS_SKILL = 4;

CHAR2_BASE_ATK = 6;
CHAR2_BONUS_ATK = 1;
CHAR2_BASE_SKILL = 30;
CHAR2_BONUS_SKILL = 6;