
-- SPEED : 타일 한 칸을 이동하는 데 걸리는 시간. 즉 낮을수록 빠름. miliseconds 단위.
-- MOVETYPE 1 - PIECE : 때리기 전에는 가만히
-- MOVETYPE 2 - AGRO : 근처 영역에 접근하면 쫓아 오기
-- WAITTYPE 1 - FIXED : 자기 자리에 가만히 있음
-- WAITTYPE 2 - ROAMING : 원래 위치 주변을 배회

MONSTER0_NAME = "SHROOM"
MONSTER0_LEVEL = 2
MONSTER0_EXP = 12
MONSTER0_HP = 30
MONSTER0_SPEED = 1200
MONSTER0_ATK = 5
MONSTER0_MOVETYPE = 1
MONSTER0_WAITTYPE = 1

MONSTER1_NAME = "MUSHROOM"
MONSTER1_LEVEL = 3
MONSTER1_EXP = 18
MONSTER1_HP = 40
MONSTER1_SPEED = 1000
MONSTER1_ATK = 8
MONSTER1_MOVETYPE = 1
MONSTER1_WAITTYPE = 2

MONSTER2_NAME = "RIBBONPIG"
MONSTER2_LEVEL = 4
MONSTER2_EXP = 70
MONSTER2_HP = 21
MONSTER2_SPEED = 1200
MONSTER2_ATK = 12
MONSTER2_MOVETYPE = 2
MONSTER2_WAITTYPE = 2